//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySanPhamDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<double> TienBan { get; set; }
        public Nullable<int> MaNhomHang { get; set; }
    
        public virtual NhomHang NhomHang { get; set; }
    }
}
